name: Ubuntu - Test

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '00 1 * * *'

jobs:
  build:
    name: Test on Ubuntu
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'zulu'
      - name: Check running containers
        run: docker ps
      - name: Run all tests
        continue-on-error: true
        run: mvn test 
